create schema if not exists verndar;

create table if not exists ib_air_imports (
	"Datum provedení" date,
	"Směr úhrady" text,
	"Typ úhrady" text,
	"Kategorie plateb" text,
	"Měna účtu" text,
	"Částka v měně účtu" numeric(18,6),
	"Poplatek v měně účtu" numeric(18,6),
	"Původní měna úhrady" text,
	"Původní částka úhrady" numeric(18,6),
	"Název protistrany" text,
	"Číslo účtu protistrany" text,
	"Název účtu protistrany" text,
	"Variabilní symbol" text,
	"Konstantní symbol" text,
	"Specifický symbol" text,
	"Zdrojová obálka" text,
	"Cílová obálka" text,
	"Poznámka pro mne" text,
	"Zpráva pro příjemce" text,
	"Poznámka k úhradě" text,
	"Název karty" text,
	"Číslo karty" text,
	"Držitel karty" text,
	"Název zařízení" text,
	"Obchodní místo" text,
	"Směnný kurz" numeric(18,6),
	"Odesílatel poslal" text,
	"Poplatky jiných bank" numeric(18,6),
	"Datum a čas zadání" timestamptz,
	"Datum splatnosti" date,
	"Datum schválení" date,
	"Datum zaúčtování" date,
	"Referenční číslo" bigint primary key,
	"Způsob zadání" text,
	"Zadal" text,
	"Zaúčtováno" text,
	"Pojmenování příkazu" text,
	"Název, adresa a stát protistrany" text,
	"Název, adresa a stát banky protistrany" text,
	"Typ poplatku" text,
	"Účel úhrady" text,
	"Zvláštní pokyny k úhradě" text,
	"Související úhrady" text,
	"Další identifikace úhrady" text,
	"Způsob úhrady" text
);